POST http://localhost:3000/api/v1/characters
Content-Type: application/json

{
    "nombre": "Bruno",
    "apellido": "Pie",
    "puntaje": "82",
    "habilidad": "Super patada"
}

###
GET http://localhost:3000/api/v1/characters

###
PATCH  http://localhost:3000/api/v1/characters/{id}
Content-Type: application/json

{
    "nombre": "Herald"
}

###
DELETE http://localhost:3000/api/v1/characters/{id}