POST http://localhost:3000/api/v1/characters
Content-Type: application/json

{
    "nombre": "Bno",
    "apellido": "Pie",
    "puntaje": "82",
    "habilidad": "Super patada"
}

###
GET http://localhost:3000/api/v1/characters

###
PATCH  http://localhost:3000/api/v1/characters/se721r77-98yf-x910-9bx2-8cb0x1x9083v
Content-Type: application/json

{
    "nombre": "Herald"
}

###
DELETE http://localhost:3000/api/v1/characters/6b86332a-d7bc-4bb9-bc24-72f8fce7572b1